### ISSUE TITLE
Replace eslint-import-resolver-node and eslint-import-resolver-typescript?

### ISSUE THREAD

**Issue by ModyQyW** [9romise/eslint-import-resolver-oxc#18]
Hello, I stumbled upon this project and first of all I would like to thank you for your work on this project.

I've read some of the documentation, but I'm still unsure if this project can replace eslint-import-resolver-node and eslint-import-resolver-typescript? It must be a good optimization for performance!

**Comment by 9romise** [comment]
Yes, it is a good replacement for eslint-import-resolver-typescript.

[eslint-react](https://github.com/Rel1cx/eslint-react) is using this now.

Thank you for your feedback, I will improve the document later.

**Comment by ModyQyW** [comment]
Just opened a PR for this. I hope I can do some help. :D
