### ISSUE TITLE
Add jsconfig.json support

### ISSUE THREAD

**Issue by vladshcherbin** [9romise/eslint-import-resolver-oxc#45]
Hey 👋 

It would be nice if `jsconfig.json` would be used if it exists in the root directory, similar to `tsconfig.json`.

**Comment by 9romise** [comment]
Sounds good! I will try it as soon, and thanks for your interest in this project!

**Comment by vladshcherbin** [comment]
@9romise wow that was fast 😅

Thank you a lot, I've been using and recommending your resolver for a few weeks and it works great so far!
